name: Symfony CI

on:
  push:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
     
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Clear Symfony cache
        run: php bin/console cache:clear --env=test

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src

      # - name: Run PHP CS Fixer
      #   run: vendor/bin/php-cs-fixer fix src --dry-run --diff

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Notify GitHub (trigger merge develop to test)
        if: ${{ success() }}
        run: |
          curl -X POST https://api.github.com/repos/PaulineFranck98/finalProjectCDA/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -d '{"event_type":"trigger-merge-symfony"}'